name := "EventSourcing Fun"
version := "1.0.0"
scalaVersion := "2.11.7"


libraryDependencies += "org.scalatest" % "scalatest_2.11" % "2.2.4" % "test"
libraryDependencies += "com.typesafe.akka" % "akka-stream-experimental_2.11" % "1.0"
libraryDependencies += "com.typesafe.akka" % "akka-http-core-experimental_2.11" % "1.0"
libraryDependencies += "com.typesafe.akka" % "akka-http-experimental_2.11" % "1.0"
libraryDependencies += "com.typesafe.akka" %% "akka-http-spray-json-experimental" % "1.0"
libraryDependencies += "org.json4s" % "json4s-native_2.11" % "3.3.0.RC5"
libraryDependencies += "org.json4s" % "json4s-ext_2.11" % "3.3.0.RC5"
libraryDependencies += "de.heikoseeberger" %% "akka-http-json4s" % "1.1.0"
libraryDependencies += "joda-time" % "joda-time" % "2.8.2"
libraryDependencies += "com.websudos"  %% "phantom-dsl" % "1.10.1"
// libraryDependencies += "com.websudos" %% "phantom-testkit" % "1.10.1" % "test, provided"
//libraryDependencies += "io.spray" %%  "spray-json" % "1.3.2"
